//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICE_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int ID { get; set; }
        public string Text { get; set; }
        public int EmergencyID { get; set; }
    
        public virtual EmergencyTypes EmergencyTypes { get; set; }
    }
}
